### ISSUE TITLE
请求头设置

### ISSUE THREAD

**Issue by nicong622** [xiaoqiujun/wxHttp#13]
在设置请求头的时候，原版 axios 用的是 headers ，微信小程序和这里都是用 header，少了一个字母 ‘s’。感觉做一下兼容会好一点。如何传了 headers，就把 headers 也 merge 到 header 里。或者起码在文档里注明一下这个差异。

**Comment by xiaoqiujun** [comment]
非常感谢宝贵的建议，会及时作出相应的bug修复

**Comment by xiaoqiujun** [comment]
非常感谢宝贵的建议，会及时作出相应的bug修复
